### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by smoes** [WietseWind/rippled-ws-client#1]
In my quest of making alivingledger serverless, I tried to include rippled-ws-client in my **clojurescript** application. It uses the standard npm build with rippled-ws-client in version "1.0.0". When building the project I get the error bellow.

I'm not entirely sure if this is a problem with my clojurescript setup or a pure js problem. Concerning the second I'm hoping that you maybe can quickly figure out what the problem is. I'm not a pure javascript crack :) 

```
Compiling build :dev to "resources/public/js/compiled/ledger-observer.js" from ["src"]...
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Can't resolve 'events' in '/home/smoes/git/ledger-observer/node_modules/rippled-ws-client/src'
    at onError (/home/smoes/git/ledger-observer/node_modules/enhanced-resolve/lib/Resolver.js:61:15)
    at loggingCallbackWrapper (/home/smoes/git/ledger-observer/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/smoes/git/ledger-observer/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/smoes/git/ledger-observer/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/smoes/git/ledger-observer/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/smoes/git/ledger-observer/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/home/smoes/git/ledger-observer/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/home/smoes/git/ledger-observer/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/smoes/git/ledger-observer/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/home/smoes/git/ledger-observer/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
```

Maybe helpful:

``` 
$ npm -v
3.5.2
```

Any idea? There is a high chance this is related to my clojurescript setup since the enhanced-resolve npm thingy is error prone when used with cljs.

**Comment by smoes** [comment]
I may add that there is another method to include your lib in a cljs project, serving a standalone js as a foreign lib. I haven't tried this method yet since upgrading versions involves a lot of manual steps. Maybe that will work.

**Comment by WietseWind** [comment]
Hey, I'm almost sure you're missing `events`:

![image](https://user-images.githubusercontent.com/4756161/45261301-9608ed80-b3ff-11e8-835a-aefc044bd1e1.png)
(First line, your stack trace: `Error: Can't resolve 'events' in '/home/smoes/git/ledger-observer/node_modules/rippled-ws-client/src'`)

I don't know anything about ClojureScript, but my guess is that `require()` in ClojureScript wants to load Events, while this code is ES6, pointing to [node Events](https://nodejs.org/api/events.html).

**Comment by smoes** [comment]
That's what I suspected, too. I know this is not how we usually handle things, but I would close the issue for now. I currently have only very little spare time left and implemented the web-socket in a short time myself, since I only need subscribe tx in the first place. If I have another few hours over, I'll have a look at it again and provide a gist how to use your lib from clojurescript.

Thank you for your time, keep up the good work!

**Comment by WietseWind** [comment]
Thanks man! And it may help to browserify this repo and use the precompiled JS?

**Comment by smoes** [comment]
Does the precompiled JS have dependencies? Whatever, I think it would help, yes. Unmanaged dependencies are easier to handle.
